---
name: test-actions
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.8.7

      - uses: ./
